name: Trigger HL7 FHIR Autobuild
run-name: ${{ github.actor }} triggered a GitHub Action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          curl --request POST \
          --header 'content-type: application/json' \
          --url https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger \
          --data '{"ref": "refs/heads/master", "repository": {"full_name": "costateixeira/testworkflows"}}'
   
  
#      - name: Start HL7 Webhook
#        uses: joelwmale/webhook-action@master
#        with:
#          url: https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger
#      - name: Start HL7 Webhook
#        uses: distributhor/workflow-webhook@v2.0.4
#        env:
#          webhook_url: https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger
#          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
